app = "bestiapp"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "recreate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 100
  soft_limit = 80

[[mounts]]
  source = "dati_classifica"
  destination = "/data"

[env]
  DATABASE_URL = "sqlite:////data/camp.db"

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"
